/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_jnitest_JniResource */

#ifndef _Included_com_jni_jnitest_JniResource
#define _Included_com_jni_jnitest_JniResource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_jnitest_JniResource
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_mytestproject_JniResource_hello
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_jnitest_JniResource
 * Method:    showToast
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_test_mytestproject_JniResource_showAddToast
  (JNIEnv *, jobject,jint, jint);

JNIEXPORT void JNICALL Java_com_test_mytestproject_JniResource_showDelToast
  (JNIEnv *, jobject,jint, jint);

#ifdef __cplusplus
}
#endif
#endif
